### PR TITLE
Json schema

### PR DESCRIPTION
**Pull request by ifitzpatrick**
This pull request includes a bunch of changes:
- Make schemas json schema compliant
- Use features of json schema to reduce duplicated schema items
- Unit tests to make sure schema features are being used correctly
- fbp-test uses schemas for validation
- some new grunt tasks for converting yaml to json, building a js file with all the schemas, and running new unit tests
- A couple of small changes to the protocol files, accounting for some properties that are expected by fbp-test but weren't actually spelled out in the schemas
- A file that gathers up the schemas and add them to tv4 that we can expose as a library to fbp systems that want to use the schemas to validate incoming protocol events such as noflo-ui
- Uses schemas to generate docs for messages. Currently using a grunt task to generate each line of markdown.

The new schemas can test that required properties of events are present, prevent validation with extra unwanted properties while allowing for optional ones, and validate formatting constraints such as date time strings.

Relevant issues:
https://github.com/flowbased/fbp-protocol/issues/13
https://github.com/flowbased/fbp-protocol/issues/14

### CODE REVIEW

**Comment by ifitzpatrick** [comment]
Is there a reference runtime that the tests that are run by travis should point to?

**Comment by jonnor** [comment]
Wow, huge PR ;). Overall I really like the changes, especially that the schemas are now canonical, and that they have tests.

Did you go over the descriptions in the YAML files and update them based on what we currently have/had in the README? I believe that the README was the most up to date.
You say there were a couple of small changes, can you enumerate or give some examples of these?

I also think that now that we have one datasource, we should stop checking in generated variants.
So both the README, the schema/json/*.json files, and the schemas.js should be removed from git. We'd have it included the website (which is automatically built in master), and in NPM packages (I can set up autodeploy here).
However, this can be done in a follow-up PR.

**Comment by jonnor** [comment]
@ifitzpatrick I see that there are `.js` versions of `.coffee` files included everywhere. Please remove them from git, and add the respective directories to `.gitignore` so it does not happen again accidentially.

```
 [jon@jon-laptop fbp-protocol]$ git ls-files | grep -e '.js$'
schema/format.js
schema/index.js
schema/schemas.js
src/Config.js
src/WebSocket.js
test/schema/test_component.js
test/schema/test_graph.js
test/schema/test_network.js
test/schema/test_runtime.js
```

**Comment by jonnor** [comment]
@ifitzpatrick I took a quick look over the changes to protocol/spec.md. It mostly looks good, however there are several issues that need fixing:

* Only the top-level attributes of payload shows up. Affects basically everwhere we refer to edges (`src` and `tgt`). Also for `component:component` message, `runtime:ports`. Right now I think this should stay rendered inline, like before. Alternative is link which takes one to the doc for the compound datatype (for instance `_Edge_`)
* Network: `begingroup`, `data`, `endgroup` are completely missing payload descriptions. Guess missing in schemas?
* Graph: `addinitial` missing description for `src`

**Comment by ifitzpatrick** [comment]
@jonnor thanks for your feedback! I think that there's a bug in the build process for the documentation that is causing the missing descriptions and nested properties for src/tgt etc. Those things are in the schemas. I did go through the original spec.md and updated everything that I saw was different from the yaml schemas. The small changes I was referring to were discrepancies between spec.md and the schemas. I'll get a list together of the changes I made and post them here before we merge.

**Comment by ifitzpatrick** [comment]
@jonnor The intention for index.js and it's dependencies schemas.js and format.js is that they will eventually be used as a library in other applications to validate schema messages. The json files are only required for the build so I don't see a problem removing those or the js files that are built for the tests, but I'm not sure that we should remove the js files in schema/ so that they can be required by other apps through npm or bower.

**Comment by jonnor** [comment]
@ifitzpatrick we can easily (and should) include the generated .js files in the NPM package, without them being in git.

**Comment by ifitzpatrick** [comment]
Ah great I'll remove those

**Comment by ifitzpatrick** [comment]
Here are the properties that were added to the schemas. All of them were present in the docs before, except for `debug` on started and stopped, which I added because fbp-test expects it.

network:stopped
* running
* started
* debug

network:started
* running
* started
* debug

network:status
* started
* debug

**Comment by jonnor** [comment]
Thanks a lot! I've now set up autodeploy to NPM on tags, and released `fbp-protocol 0.2.5` which has this PR in.

**Comment by chadrik** [comment]
Should we make the npm version match the protocol version?

**Pull request merged**
